<?php

namespace api\controllers;

use common\services\Sms;
use Yii;
use yii\base\Exception;
use yii\base\ExitException;
use yii\data\Pagination;
use yii\data\Sort;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use common\services;

/**
 * CountryController implements the CRUD actions for Country model.
 */
class SmsController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function beforeAction($action)
    {
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * Lists all Country models.
     * @return mixed
     */
    public function actionIndex()
    {
    }


    public function actionSms()
    {
        $gf = new GlobalFunction();
        $result = $gf->sendText('15210061902','测试下内容');
        var_dump($result);
    }

    /**
     * Deletes an existing Country model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionBatchSend()
    {
        $sms = new Sms();
        $result = $sms->batchSend('18600862625','旅游局告知：您与北京神舟国际旅行社集团有限公司签订的出团日期为2016年01月09日的合同已经上传至第三方备案 【神舟旅游】');
        var_dump($result);
    }

    public function actionSend($m){
        $sms = new Sms();
        $result=$sms->batchSend($m,Sms::$MesTemp[Sms::MES_TEMP_SIGN]);
        var_dump_die($result);
    }

    public function actionHl(){
        //验证码：041053（有效时间5分钟，如非本人操作，请忽略。）【汇来科技】
        $sms = new Sms();
        $result = $sms->batchSend('15210061902','验证码：041332（有效时间5分钟，如非本人操作，请忽略。）链接 http://www.btgerp.com【神舟旅游】');
        var_dump($result);
    }

    public function actionSel(){
        try{
            $sms = new Sms();
            $result=$sms->selSum();
            var_dump_die($result);
        }catch (Exception $e){
            var_dump_die($e->getMessage());
        }
    }

}
